### ISSUE TITLE
Problem with Bootstrap 4.4 / Responsive containers

### ISSUE THREAD

**Issue by nvindice** [scssphp/scssphp#69]
In Bootstrap 4.4 a feature called "responsive containers" was added, see: https://github.com/twbs/bootstrap/pull/25631

However, the corresponding functions do not compile right with scssphp:

Original Bootstrap 4.4.1 compiled CSS:
```
@media (min-width:768px) {
 .container,
 .container-md,
 .container-sm {
  max-width:720px
 }
}
```

CSS compiled with scssphp results in:
```
@media (min-width: 768px) {
  .container-md {
    max-width: 720px; 
  }
}
```

The bootstrap code used to create these pieces of css can be found here: https://github.com/twbs/bootstrap/blob/master/scss/_grid.scss#L17-L45

**Comment by Cerdic** [comment]
Debugging on a full Bootstrap compilation is almost impossible. 

It would be super helpful if you can reproduce with a minimal piece of code and allow to fix that super quickly then :)

**Comment by nvindice** [comment]
Hi @Cerdic, thanks for your reply. I made a minimal test case containing only the relevant Bootstrap 4.4.1 variables and functions:

```
// boostrap-4.4.1/scss/_variables.scss:198-207
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;

// boostrap-4.4.1/scss/_variables.scss:214-221
$container-max-widths: (
  sm: 540px,
  md: 720px,
  lg: 960px,
  xl: 1140px
) !default;

// boostrap-4.4.1/scss/_breakpoints.scss:26-29
@function breakpoint-min($name, $breakpoints: $grid-breakpoints) {
  $min: map-get($breakpoints, $name);
  @return if($min != 0, $min, null);
}

// boostrap-4.4.1/scss/_breakpoints.scss:52-54
@function breakpoint-infix($name, $breakpoints: $grid-breakpoints) {
  @return if(breakpoint-min($name, $breakpoints) == null, "", "-#{$name}");
}

// boostrap-4.4.1/scss/_breakpoints.scss:58-67
@mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  @if $min {
    @media (min-width: $min) {
      @content;
    }
  } @else {
    @content;
  }
}

// boostrap-4.4.1/scss/_grid.scss:18-35
@each $breakpoint, $container-max-width in $container-max-widths {
  // ...
  @include media-breakpoint-up($breakpoint, $grid-breakpoints) {
    %responsive-container-#{$breakpoint} {
	  max-width: $container-max-width;
    }

    @each $name, $width in $grid-breakpoints {
	  @if ($container-max-width > $width or $breakpoint == $name) {
	    .container#{breakpoint-infix($name, $grid-breakpoints)} {
		  @extend %responsive-container-#{$breakpoint};
	    }
	  }
    }
  }
}
```

Expected output (see e.g. https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.css#L546-L568 ):

```
@media (min-width: 576px) {
  .container, .container-sm {
    max-width: 540px;
  }
}

@media (min-width: 768px) {
  .container, .container-sm, .container-md {
    max-width: 720px;
  }
}

@media (min-width: 992px) {
  .container, .container-sm, .container-md, .container-lg {
    max-width: 960px;
  }
}

@media (min-width: 1200px) {
  .container, .container-sm, .container-md, .container-lg, .container-xl {
    max-width: 1140px;
  }
}
```

Output from scssphp:
```
@media (min-width: 576px) {
  .container-sm {
    max-width: 540px; 
  }
}

@media (min-width: 768px) {
  .container-md {
    max-width: 720px;
  }
}

@media (min-width: 992px) {
  .container-lg {
    max-width: 960px;
  }
}

@media (min-width: 1200px) {
  .container-xl {
    max-width: 1140px;
  }
}
```

Looks like a problem with extensions / placeholder selectors to me.

**Comment by Cerdic** [comment]
> Looks like a problem with extensions / placeholder selectors to me.

Indeed! Thanks, I dig on that as soon as possible!

**Comment by Cerdic** [comment]
Was able to reduce even more the test case:
```
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
) !default;

$container-max-widths: (
  sm: 540px,
) !default;

@function breakpoint-infix($name, $breakpoints: $grid-breakpoints) {
  @return "-#{$name}";
}

@mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
  @content;
}

@each $breakpoint, $container-max-width in $container-max-widths {
  @include media-breakpoint-up($breakpoint, $grid-breakpoints) {
    %responsive-container-#{$breakpoint} {
      max-width: $container-max-width;
    }

    @each $name, $width in $grid-breakpoints {
      .container#{breakpoint-infix($name, $grid-breakpoints)} {
        @extend %responsive-container-#{$breakpoint};
      }
    }
  }
}
```
gives with sassmeister:
```
.container-sm, .container-xs {
  max-width: 540px;
}
```
but scssphp gives
```
.container-sm {
  max-width: 540px; }
```

IF you're removing the `@include media-breakpoint-up` (which only is a `@content` mixin) OR replacing `#{breakpoint-infix($name, $grid-breakpoints)}` with `-#{$name}` (which is the same) it gives the good result with scssphp. 

Changing the placeholder for a normal class still produces the bug.

So it seems linked to extend context and/or extend computed name when computing the extend list

**Comment by Cerdic** [comment]
digging in it, this NOT an extend issue but a calling scope/context issue with the combined function and mixin making that the arguments values in the function `breakpoint-infix` have the same value at each call.

Searching for the base cause to be able to fix without breaking anything else

**Comment by Cerdic** [comment]
At the end `@each` was the guilt structure here, with some mistake about where to store the `key`, `value` vars.

This is solved now!

**Comment by nvindice** [comment]
Awesome, thank you!

**Comment by incohe** [comment]
Hi Im using the latest bootstrap release 4.5.3 but apparently i still encounter this issue. may i ask when this will be fixed?

Thanks

**Comment by Cerdic** [comment]
This has been fixed one year ago. At least the original report.
Maybe you can give more information, like the version of scssphp you are using, more detail about your issue, and what you get on the test cases above? Whatever this should be a new issue pointing this one for full context

**Comment by PrestaSafe** [comment]
hi i'm facing the same issue. I've the latest version of scssphp, do you have a tips for fixing that ? Thanks.

**Comment by stof** [comment]
@PrestaSafe please open a new issue with details rather than commenting on a closed issue
